[package]
name = "bevy_enoki"
version = "0.4.0"
edition = "2021"

[dependencies]
bevy = "0.16.1"
serde = { version = "1.0.197", features = ["derive"] }
ron = "0.10"
rand = { version = "0.8.5" }

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
